on:
  push:
    branches: 
      - main
name: Azure APIM
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Bicep file
    - name: deploy in APIM
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: 'integrate-2025'
        template: integration/order-processing/main.bicep
        parameters: integration/order-processing/params.json
        failOnStdErr: false

    - name: register in API Center
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az apic api register -g integrate-2025 -n integrate-2025 -l integration/order-processing/order-api.openapi-v2.json
